sudo: required
language: python
python:
  - "2.7"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - sudo apt-get -qq install xvfb tcpdump wireshark
  - pip install -r requirements.txt
  - python setup.py
before_script:
  - cd test  
script:  py.test -k 'not dumputils_test.py'
after_script:
  - which dumpcap
  - sudo timeout 10 dumpcap -w /tmp/abc.pcap
  - echo $?
  - ls -la /tmp/abc.pcap

