galaxy_info:
  author: Rafael Gálvez Vizcaíno
  company: ESAT/COSIC KU Leuven

  license: license (BSD)

  min_ansible_version: 2.2

  platforms:
  
  - name: Debian
    versions:
      - jessie

dependencies:
  - { role: parmegv.ansible-custom-tor, custom_tor_src_dir: "{{ tor_path }}" }
  - { role: parmegv.ansible-onionperf }
